# -*- coding: utf-8 -*-
"""starter_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfvB1ewBll0DCKskbzfUwmb-c-GS8IDx
"""

import random

NUM_ROUNDS = 5

def main():
    print("Welcome to the High-Low Game!")
    print('--------------------------------')

    score = 0

    for round_num in range(1, NUM_ROUNDS + 1):
        print(f"Round {round_num}")
        print('--------------------------------')

        user_num = random.randint(1, 100)
        computer_num = random.randint(1, 100)

        print(f"Your number is: {user_num}")

        guess = input("Do you think your number is higher or lower than the computer's? (higher/lower): ").strip().lower()

        while guess not in ["higher", "lower"]:
          guess = input("Please enter either 'higher' or 'lower': ").strip().lower()

        if (guess == "higher" and user_num > computer_num) or (guess == "lower" and user_num < computer_num):
            print(f"You were right! The computer's number was {computer_num}")
            score += 1
        else:
            print(f"Aww, that's incorrect. The computer's number was {computer_num}")

        print(f"Your score is now {score}\n")

    print("Thanks for playing!")

    if score == NUM_ROUNDS:
        print("Wow! You played perfectly!")
    elif score >= NUM_ROUNDS // 2:
        print("Good job, you played really well!")
    else:
        print("Better luck next time!")

if __name__ == "__main__":
    main()