# -*- coding: utf-8 -*-
"""Index_Game_Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcnfgBstP3nAV_3GVVl2AgSXDjM72boB
"""

def access_elements(lst, index):
    try:
        return lst[index]
    except IndexError:
        return "Index out of range."

def modify_elements(lst, index, new_value):
    try:
        lst[index] = new_value
        return lst
    except IndexError:
        return "Index out of range."

def slice_lst(lst, start, end):
    try:
        return lst[start:end]
    except IndexError:
        return "Invalid indices."


def index_games():
    lst = [1, 2, 3, 4, 5]
    print("\nCurrent list:", lst)
    print("Choose an operation: access, modify, slice")
    operation = input("Enter operation: ")

    if operation == "access":
        index = int(input("Enter index to access: "))
        print("Result:", access_elements(lst, index))
    elif operation == "modify":
        index = int(input("Enter index to modify: "))
        new_value = input("Enter new value: ")
        print("Updated List:", modify_elements(lst, index, new_value))
    elif operation == "slice":
        start = int(input("Enter start index: "))
        end = int(input("Enter end index: "))
        print("Sliced List:", slice_lst(lst, start, end))
    else:
        print("Invalid operation.")

def list_practice():
    print("\nList Practice")

    fruit_lst = ['apple', 'banana', 'orange', 'grape', 'pineapple']

    lst_length = len(fruit_lst)
    print("List Length:", lst_length)

    fruit_lst.append('mango')

    print("Updated List:")
    for fruit in fruit_lst:
        print(fruit)


def main():
    list_practice()
    index_games()

if __name__ == "__main__":
    main()