# -*- coding: utf-8 -*-
"""00_joke_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTunRdWUk5_TqsaEJN3vrUFQZqHRZklS
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

PROMPT = f"What do you want? {CBLUE}"
JOKE = f"{CWHITE}Here is a joke for you! Sophia is heading out to the grocery store. A programmer tells her: get a liter of milk, and if they have eggs, get 12. Sophia returns with 13 liters of milk. The programmer asks why and Sophia replies: 'because they had eggs'"
SORRY = f"{CWHITE}Sorry I only tell jokes."

def main():
    user_input = input(PROMPT).strip().lower()

    if (user_input == "joke"):
      print(JOKE)
    else:
      print(SORRY)



if __name__ == '__main__':
    main()