# -*- coding: utf-8 -*-
"""02_liftoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3IWDM6FMEuL5ZgidYHgVQsBG3wg5qCy
"""

def main():
    for i in range(10, 0, -1):
      print(i, end=" ")
    print("Liftoff!")


if __name__ == '__main__':
    main()